INSERT INTO USER (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ENABLED, GENDER) VALUES ('user', 'password',  'Serkan', 'OZAL', 1, 1);

INSERT INTO ROLE (NAME) VALUES('Member');
INSERT INTO ROLE (NAME) VALUES('Admin');

INSERT INTO USER_ROLE (SELECT usr.ID, r.ID FROM USER usr, ROLE r where r.name ='Member');
INSERT INTO USER_ROLE (SELECT usr.ID, r.ID FROM USER usr, ROLE r where r.name ='Admin');

INSERT INTO PERMISSION (NAME) VALUES('MEMBER_GET_PERM');
INSERT INTO PERMISSION (NAME) VALUES('MEMBER_LIST_PERM');
INSERT INTO PERMISSION (NAME) VALUES('MEMBER_UPDATE_PERM');
INSERT INTO PERMISSION (NAME) VALUES('MEMBER_DELETE_PERM');
INSERT INTO PERMISSION (NAME) VALUES('ADMIN_GET_PERM');
INSERT INTO PERMISSION (NAME) VALUES('ADMIN_LIST_PERM');
INSERT INTO PERMISSION (NAME) VALUES('ADMIN_UPDATE_PERM');
INSERT INTO PERMISSION (NAME) VALUES('ADMIN_DELETE_PERM');

INSERT INTO ROLE_PERMISSION (SELECT r.ID, perm.ID FROM PERMISSION perm, "ROLE" r WHERE r.name ='Member');
INSERT INTO ROLE_PERMISSION (SELECT r.ID, perm.ID FROM PERMISSION perm, "ROLE" r WHERE r.name ='Admin');

COMMIT;
